version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: .*  # This regex directs all routes to main.app
  script: api.main.app

libraries:
- name: ssl
  version: latest

builtins:
- deferred: on
- remote_api: on